### ISSUE TITLE
BasemapGallery.AvailableBasemaps items not displaying after object instantiation

### ISSUE THREAD

**Issue by williambohrmann3** [Esri/arcgis-maps-sdk-dotnet-toolkit#487]
There is a lag in displaying `BasemapGallery.AvailableBasemaps` after setting it to a `List<Basemap>` or `ObservableCollection<Basemap>`. The gallery will keep displaying old basemaps. `BasemapGallery.AvailableBasemaps` will update just fine, as verified by comparing the old count to the new count - the issue is displaying the basemaps in the gallery immediately after. It requires setting `BasemapGallery.AvailableBasemaps` to two objects (List or ObservableCollection) before the UI is up to date. Simply waiting patiently for the gallery to update will not work.

The issue persists in these two cases:
- instantiating the object to a var `galleryItems`, then setting `AvailableBasemaps` to `galleryItems`
- directly setting `AvailableBasemaps` to a new object.

The gallery will update as expected if calling:
`BasemapGallery.AvailableBasemaps.Clear();
BasemapGallery.AvailableBasemaps.Add();`

See the reproducer:
[testgeonet.zip](https://github.com/Esri/arcgis-maps-sdk-dotnet-toolkit/files/10680446/testgeonet.zip)

**Comment by dturrina** [comment]
I noticed that, in MAUI, you may set the AvailableBasemap property correctly, but the default gallery loading task takes some time to perform, so that in the end the new (default) gallery completely overwrites the old (custom) one. I think a check on whether a value is already given or not should be performed before loading default basemaps (also to eventually improve performances).

**Comment by williambohrmann3** [comment]
@dturrina This issue has been fixed and merged (see #492)! Now when applying the template, the ListView uses the controller as the source and a path of available basemaps.
